server:
  port: 8082
  servlet:
    context-path: /social/api

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/social_network
    username: otus
    password: otus
    driver-class-name: com.mysql.cj.jdbc.Driver

security-settings:
  url-whitelist:
    /auth,
    /ping,
    /register